#!/usr/bin/bash
#//Script Kiddies//
kiddies='\e[1;31m'
kiddes='\e[1;33m'
clear
echo ""
figlet " INSTAGRAM TOOLS" | lolcat
echo -e $kiddes "#####################"
echo "  # CYBER TEAM # " | lolcat
echo "  # CREATED BY : MR.Z # " | lolcat
echo -e $kiddes "#####################"
echo -e $kiddies"=======================================" 
echo " [1] INSTAGRAM BOT"  | lolcat
echo " [2] INSTAGRAM HACK" | lolcat
echo -e $kiddies"======================================="
read -p " [Chose The Number]> " Instagram;

if [ $Instagram = 1 ] || [ $Instagram = 1 ]
then
echo "================================================"
python2 igbot.py;
fi

if [ $Instagram = 2 ] || [ $Instagram = 2 ]
then
echo "================================================"
python2 ighack.py;
fi
