#!/usr/bin/bash
#//Script Kiddies//
kiddies='\e[1;31m'
kiddes='\e[1;33m'
clear
echo ""
figlet " INSTAGRAM TOOLS" | lolcat
echo -e $kiddes "#####################"
echo "  # CYBER TEAM # " | lolcat
echo "  # CREATED BY : MR.Z # " | lolcat
echo "  # WARNING : DON'T RE-EDIT MY SCRIPT,YOU CAN GET ERROR # " | lolcat
echo -e $kiddes "#####################"
echo -e $kiddies"=======================================" 
echo " [1] INSTAGRAM BOT"  | lolcat
echo " [2] INSTAGRAM HACK" | lolcat
echo -e $kiddies"======================================="
read -p " [Chose The Number]> " insta;

if [ $insta = 1 ] || [ $insta = 1 ]
then
echo "================================================"
python2 instabot.py;
fi

if [ $insta = 2 ] || [ $insta = 2 ]
then
echo "================================================"
python2 instahack.py;
fi
